version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build: .
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8000:80

  db:
    image: mysql:5.7
  #  volumes:
  #    - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_PORT=3306
      - PMA_USER=user
      - PMA_PASSWORD=root
    ports:
      - 8101:80
  # php-apache-environment:
  #   container_name: php-apache
  #   image: php:8.0-apache
  #   volumes:
  #     - ./src:/var/www/html/
  #   ports:
  #     - 8000:80